#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan  7 12:44:26 2020

@author: baptistebignaud
"""


def I(L_jobs):
    N=len(L_jobs)
    I=np.zeros(N,N)
    for i in range (N):
        for j in range(N):
            I[i][j]=I_ij(L_jobs)
    return I

def W(L_jobs):
    N=len(L_jobs)
    Wl=np.zeros(N,N,N,N):
        for i in range(N):
            for j in range(N):
                for k in range(N):
                    for l in range(N):
                        W[i][j][k][l]=W_ijkl(i, j, k, l)
    return W
